source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
  project 'MWPhotoBrowser.xcodeproj'
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  project 'MWPhotoBrowser.xcodeproj'
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
   pod 'FBSnapshotTestCase', '~> 1.8.1'
  pod 'Expecta+Snapshots'
end
